from zope.i18nmessageid import MessageFactory
#from senaite.patient.catalog import PATIENT_CATALOG  # noqa

_ = MessageFactory("hoch.lims")

PRODUCT_NAME = "hoch.lims"

DEFAULT_ROLES = ("Manager", )

DEFAULT_TYPES = ("MarketingAuthorizations", 
                "MarketingAuthorization", 
                "PharmaceuticalProduct",)

AUTO_ID_MARKER = "-- autogenerated --"
