# -*- coding: utf-8 -*-
from zope.i18nmessageid import MessageFactory

_ = MessageFactory("hoch.lims")

PRODUCT_NAME = "hoch.lims"

DEFAULT_ROLES = ("Manager", )

DEFAULT_TYPES = ("MarketingAuthorizations", 
                "MarketingAuthorization", 
                "PharmaceuticalProduct",)

AUTO_ID_MARKER = "-- autogenerated --"

REGULATORY_AUTHORITIES = (
    (u"AGEMED", _(u"AGEMED")),
    (u"DIGEMID", _(u"DIGEMID")),
    (u"ANMAT", _(u"ANMAT")),
    (u"INVIMA", _(u"INVIMA")),
    (u"ISP", _(u"ISP Chile")),
    (u"COFEPRIS", _(u"COFEPRIS")),
)

DOSAGE_FORMS = (
    (u"tablet", _(u"Tablet")),
    (u"capsule", _(u"Capsule")),
    (u"solution", _(u"Solution")),
    (u"suspension", _(u"Suspension")),
    (u"cream", _(u"Cream")),
    (u"ointment", _(u"Ointment")),
    (u"lotion", _(u"Lotion")),
    (u"injection", _(u"Injection")),
    (u"powder", _(u"Powder for solution")),
)

PRODUCT_LINES = (
    (u"brand", _(u"Brand")),
    (u"generic", _(u"Generic")),
    (u"biosimilar", _(u"Biosimilar")),
    (u"otc", _(u"Over-the-counter")),
)

THERAPEUTIC_INDICATIONS = (
    (u"antibacterial", _(u"Antibacterial")),
    (u"antifungal", _(u"Antifungal")),
    (u"antiviral", _(u"Antiviral")),
    (u"analgesic", _(u"Analgesic")),
    (u"antiinflammatory", _(u"Anti-inflammatory")),
    (u"antihypertensive", _(u"Antihypertensive")),
)

SALE_CONDITIONS = (
    (u"otc", _(u"Over-the-counter (OTC)")),
    (u"rx", _(u"Prescription required")),
    (u"controlled", _(u"Controlled substance")),
)

STORAGE_CONDITIONS = (
    (u"room_temp", _(u"Room temperature (15-25°C)")),
    (u"refrigerated", _(u"Refrigerated (2-8°C)")),
    (u"frozen", _(u"Frozen (-20°C or below)")),
    (u"controlled_room", _(u"Controlled room temperature")),
)

ADMINISTRATION_ROUTES = (
    (u"oral", _(u"Oral")),
    (u"topical", _(u"Topical")),
    (u"intravenous", _(u"Intravenous")),
    (u"intramuscular", _(u"Intramuscular")),
    (u"subcutaneous", _(u"Subcutaneous")),
    (u"inhalation", _(u"Inhalation")),
)
