from zope.i18nmessageid import MessageFactory
#from senaite.patient.catalog import PATIENT_CATALOG  # noqa

_ = MessageFactory("hoch.lims")

PRODUCT_NAME = "hoch.lims"

DEFAULT_ROLES = ("Manager", )

DEFAULT_TYPES = ("MarketingAuthorizations", 
                "MarketingAuthorization", 
                "PharmaceuticalProduct",)

AUTO_ID_MARKER = "-- autogenerated --"

REGULATORS = (
    (u"FDA", _(u"FDA", default=u"FDA")),
    # ("m", _(u"authorizer_", default=u"Man")),
    # ("f", _(u"gender_woman", default=u"Woman")),
    # ("t", _(u"gender_trans", default=u"Transgender")),
    # ("d", _(u"gender_diverse", default=u"Diverse")),
    # ("", _(u"gender_not_specified", default=u"Not Specified")),
)
